# Generated by Django 3.1.7 on 2021-03-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsdetail',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=30)),
                ('pic_url', models.CharField(max_length=1000)),
                ('videourl', models.CharField(max_length=200)),
                ('mainpage', models.CharField(max_length=2000)),
                ('category', models.IntegerField()),
                ('readnum', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('password', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=500)),
            ],
        ),
    ]
