# Generated by Django 3.1.7 on 2021-03-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_auto_20210320_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tagsweight',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
