# Generated by Django 3.1.7 on 2021-03-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0004_user_tagsweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='newshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news_id', models.IntegerField()),
                ('news_hot', models.FloatField()),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='recommend',
            name='newsid',
            field=models.IntegerField(),
        ),
    ]
