# Generated by Django 3.1.7 on 2021-03-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0005_auto_20210321_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetail',
            name='orgin',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='headPortrait',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
